--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Blugin/libPluginLang-PMMP
build-by-default: true
branches:
- stable
projects:
  libTranslator:
    path: ""
    icon: "icon.png"
...
