--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Blugin/libTranslator
branches:
  - main
projects:
  libtranslator:
    model: virion
    type: library
    lint:
      phpstan: false
    libs:
      - src: Blugin/virions/LocaleConverter
        version: ^1.0.1
...