--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/libtranslator
branches:
  - main
projects:
  libtranslator:
    model: virion
    type: library
    lint:
      phpstan: false
...